/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface DonationTrackerInterface extends Interface {
  getFunction(
    nameOrSignature: "donationRecords" | "getDonationRecord" | "recordDonation"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "DonationRecorded"): EventFragment;

  encodeFunctionData(
    functionFragment: "donationRecords",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDonationRecord",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "recordDonation",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "donationRecords",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDonationRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordDonation",
    data: BytesLike
  ): Result;
}

export namespace DonationRecordedEvent {
  export type InputTuple = [
    laravelId: BigNumberish,
    amountInUSD: BigNumberish,
    donorWallet: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    laravelId: bigint,
    amountInUSD: bigint,
    donorWallet: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    laravelId: bigint;
    amountInUSD: bigint;
    donorWallet: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DonationTracker extends BaseContract {
  connect(runner?: ContractRunner | null): DonationTracker;
  waitForDeployment(): Promise<this>;

  interface: DonationTrackerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  donationRecords: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, string, bigint] & {
        laravelId: bigint;
        amountInUSD: bigint;
        donorWallet: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  getDonationRecord: TypedContractMethod<
    [_index: BigNumberish],
    [[bigint, bigint, string, bigint]],
    "view"
  >;

  recordDonation: TypedContractMethod<
    [_laravelId: BigNumberish, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "donationRecords"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, string, bigint] & {
        laravelId: bigint;
        amountInUSD: bigint;
        donorWallet: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDonationRecord"
  ): TypedContractMethod<
    [_index: BigNumberish],
    [[bigint, bigint, string, bigint]],
    "view"
  >;
  getFunction(
    nameOrSignature: "recordDonation"
  ): TypedContractMethod<
    [_laravelId: BigNumberish, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "DonationRecorded"
  ): TypedContractEvent<
    DonationRecordedEvent.InputTuple,
    DonationRecordedEvent.OutputTuple,
    DonationRecordedEvent.OutputObject
  >;

  filters: {
    "DonationRecorded(uint256,uint256,address,uint256)": TypedContractEvent<
      DonationRecordedEvent.InputTuple,
      DonationRecordedEvent.OutputTuple,
      DonationRecordedEvent.OutputObject
    >;
    DonationRecorded: TypedContractEvent<
      DonationRecordedEvent.InputTuple,
      DonationRecordedEvent.OutputTuple,
      DonationRecordedEvent.OutputObject
    >;
  };
}
